// <auto-generated />
namespace WF_Championat_Spain_Entity_Migrations_31._07.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class delete_Player_Age : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(delete_Player_Age));
        
        string IMigrationMetadata.Id
        {
            get { return "202308011210395_delete_Player_Age"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
